name: Update Walletlist from Snapshot

on:
  push:
    paths:
      - snapshot.csv

jobs:
  update-walletlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Run walletlist converter
        run: python convert_snapshot.py

      - name: Commit and Push walletlist.txt
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add walletlist.txt
          git commit -m "Update walletlist from snapshot.csv" || echo "No changes to commit"
          git push
